<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cannot add "{child}" as a child of "{parent}". "{child}" does not exist' => '',
  'Cannot add "{child}" as a child of "{parent}". Incompatible types' => '',
  'Cannot initialise; no authorisation data.' => '',
  'Default role for users that are logged in. RBAC default role.' => '',
  'Default role for users that are not logged in. RBAC default role.' => '',
  'Do you wish to re-initialise RBAC Authorisation Data?' => '',
  'Initialise RBAC Authorisation Data' => '',
  'Manages Auth Items and Role Assignments. RBAM required role.' => '',
  'Manages Auth Items. RBAM required role.' => '',
  'Manages Role Assignments. RBAM required role.' => '',
  'No changes have been made to existing RBAC Authorisation Data.' => '',
  'RBAC Authorisation Data initialised.' => '',
  'RBAC Initialisation Failed' => '',
  'RBAM has detected existing RBAC authorisation data.' => '',
  'RBAM roles have been added if not already present.' => '',
  'Re-Initialise RBAC' => '',
  'WARNING: Re-initialising will overwrite all existing RBAC Authorisation Data.' => '',
  'Would you like RBAM to generate Authorisation Data based on your application\'s modules, controllers and actions?' => '',
);
