<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'document.form.caserne' => '',
  'document.form.date' => '',
  'document.form.description' => '',
  'document.form.type' => '',
  'document.form.url' => '',
  'equipe.form.caserne' => '',
  'equipe.form.couleur' => '',
  'evenement.form.dateDebut' => '',
  'evenement.form.dateFin' => '',
  'evenement.form.nonDisponible' => '',
  'evenement.titre.a' => '',
  'evenement.titre.evenement' => '',
  'evenement.titre.formation' => '',
  'evenement.titre.moiMeme' => '',
  'evenement.titre.pour' => '',
  'formation.form.preRequis' => '',
  'formation.plan.dateDebut' => '',
  'formation.plan.dateFin' => '',
  'formation.plan.instituteur' => '',
  'formation.plan.moniteur' => '',
  'groupe.form.caserne' => '',
  'message.form.listeDestinataire' => '',
  'message.form.viderListe' => '',
  'minimum.form.caserne' => '',
  'minimum.form.dateDebut' => '',
  'minimum.form.dateFin' => '',
  'minimum.form.minimum' => '',
  'minimum.form.niveauAlerte' => '',
  'notice.form.caserne' => '',
  'notice.form.dateDebut' => '',
  'notice.form.dateFin' => '',
  'poste.form.formationObligatoire' => '',
  'usager.form.ajouterPhotoProfil' => '',
  'usager.form.ajusterPhotoProfil' => '',
  'usager.form.caserne' => '',
  'usager.form.gestionDroits' => '',
  'usager.form.gestionHoraire' => '',
  'usager.form.photoProfil' => '',
);
