<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'horaire.congeCreate.avisAbsence.notification' => '{PrenomNomPompier} a ajouté un avis d\'absence le {dateHeureAvis} pour le {dateDebut} de {heureDebut} à {heureFin} et le type de congé est {typeConge}.<br>Pour voir l\'avis cliquer {avisLien}.',
  'horaire.createModif.notification' => '{auteur} vous a ajouté à l\'horaire de garde pour le quart de {nomQuart} du {dateCaseHoraire} au poste de {nomPosteT}',
  '_listePompier.date' => 'Date',
  '_listePompier.equipe' => 'Équipe',
  '_listePompier.quart' => 'Quart',
  'dispoFDF._listePompier.date' => 'Date',
  'dispoFDF._listePompier.equipe' => 'Équipe',
  'dispoFDF._listePompier.pompierNonDispo' => 'Pompier non disponnible',
  'dispoFDF._listePompier.quart' => 'Quart',
  'dispoFDFRaportComplet.parEquipe' => 'Par equipe',
  'dispoFDFRaportComplet.parPompier' => 'Par pompier',
  'equipe.actionSaveO.enregistrementEchoue' => 'Enregistrement échoué',
  'equipe.actionSaveO.enregistrementReussi' => 'Enregistrement réussi',
  'equipe.actionSaveO.selectionMemeEquipe' => 'Vous ne pouvez choisir deux fois la même équipe',
  'equipe.ordreEquipe.aucunEquipe' => 'Aucune équipe n\'est présentement dans la force de frappe.',
  'equipeGarde.index.enregistrementReussi' => 'Enregistrement réussi',
  'horaire.pdfHoraire.setCellValue' => 'Horaire pour la période du {dateDebut}',
  'horaire.pdfHoraire.setDescription' => 'Horaire de garde du {dateDebut}',
  'horaire.pdfHoraire.setKeywords' => 'Horaire',
  'horaire.pdfHoraire.setSubject' => 'Horaire SGP',
  'horaire.pdfHoraire.setTitle' => 'Horaire',
);
