<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'usagerInvalide' => "0Usager Invalide",
  'erreur403' => 'Vous n\'avez pas les droits requis pour accéder à cette page.',
  'erreur404' => 'La page n\'a pas pu être affichée',
  'erreur409' => 'Erreur lors de la création du grade. Contactez l\'administrateur du système et donnez lui le code grade: {nomGrade}',
  'erreur500' => 'Il y a eu une erreur lors de l\'enregistrement.',
  'horaire.fermer' => '0mUne erreure est survenue lors de l\'enregistrement d\'une case horaire.',
);
