<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cannot add "{child}" as a child of "{parent}". "{child}" does not exist' => 
  'Impossible d\'ajouter "{child}" en tant qu\'enfant de "{parent}". "{child}" n\'existe pas.',
  'Cannot add "{child}" as a child of "{parent}". Incompatible types' => 
  'Impossible d\'ajouter "{child}" en tant qu\'enfant de "{parent}". Types incompatible',
  'Cannot initialise; no authorisation data.' => 'Ne peut être initialiser; Aucune donnée d\'autorisation',
  'Default role for users that are logged in. RBAC default role.' => 
  'Rôle par défaut pour les utilisateurs connectés. Rôle par défaut pour RBAC',
  'Default role for users that are not logged in. RBAC default role.' => 
  'Rôle par défaut pour les utilisateurs anonymes. Rôle par défaut de RBAC',
  'Do you wish to re-initialise RBAC Authorisation Data?' => 
  'Êtes-vous sûr de vouloir réinitialiser les données d\'autorisation de RBAC ?',
  'Initialise RBAC Authorisation Data' => 'Initialiser les données d\'autorisation de RBAC',
  'Manages Auth Items and Role Assignments. RBAM required role.' => 'Gérer les Auth Items et les rôles assignés. Requis par RBAM',
  'Manages Auth Items. RBAM required role.' => 'Gérer les Auth Items. Requis par RBAM',
  'Manages Role Assignments. RBAM required role.' => 'Gérer les rôles assignés. Requis par RBAM',
  'No changes have been made to existing RBAC Authorisation Data.' => 
  'Aucun changement fait aux informations d\'autorisation de RBAM existante',
  'RBAC Authorisation Data initialised.' => 'Données d\'autorisation de RBAC initialisé',
  'RBAC Initialisation Failed' => 'L\'inifialisation de RCAC a échoué',
  'RBAM has detected existing RBAC authorisation data.' => 'RBAM a détecté des données d\'autorisation existante',
  'RBAM roles have been added if not already present.' => 'Les rôles RBAM ont été ajoutés s\'ils n\'étaient pas déjà présent',
  'Re-Initialise RBAC' => 'Réinitialiser RBAC',
  'WARNING: Re-initialising will overwrite all existing RBAC Authorisation Data.' => 
  'AVERTISSEMENT: La réinitialisation va écraser toutes les données d\'autorisation existante.',
  'Would you like RBAM to generate Authorisation Data based on your application\'s modules, controllers and actions?' => 
  'Voulez-vous que RBAM génère les données d\'autorisation selon les modules, controlleurs et actions de votre application ?',
);
