<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'index.dispo' => 'Disponibilité',
  'index.aucunQuart' => 'Aucun quart',
  'index.caserne' => 'Caserne',
  'index.date' => 'Date',
  'index.dateActuel' => 'Date actuelle',
  'index.equipe' => 'Equipe',
  'index.forceFrappeActuelle' => 'Force de Frappe actuelle <br/> pour les deux prochains quarts:',
  'index.forceFrappeDisponnibilite' => 'Disponibilité pour la<br/>Force de Frappe:',
  'index.garde' => 'Garde',
  'index.poste' => 'Poste',
  'index.prochainsQuart' => 'Vos 3 prochains quarts de garde:',
  'index.quart' => 'Quart',
  'index.total' => 'Total',
);
