<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'document.form.caserne' => 'Sélectionner la ou les casernes où le document sera accessible.',
  'document.form.date' => 'Date servant à trier les documents.',
  'document.form.description' => 'Court texte résumant le document.',
  'document.form.type' => 'Les types de documents disponible peuvent être modifié par un administrateur.',
  'document.form.url' => 'Entrer l\'Url Youtube ou Vimeo du vidéo que vous souhaitez ajouter.',
  'document.form.file' => 'Sélectionner le fichier a envoyer sur le serveur',
  'document.form.suivi' => 'Le suivi de téléchargement vous permet de savoir à quel date et à quel heure chaque pompier a téléchargé le document',
  'equipe.form.caserne' => 'Sélectionner la caserne où l\'équipe sera utilisée.',
  'equipe.form.couleur' => 'Sélectionner la couleur qui représentera l\'équipe',
  'evenement.form.dateDebut' => 'Date et heure de début de l\'événement.',
  'evenement.form.dateFin' => 'Date et heure de fin de l\'événement.',
  'evenement.form.nonDisponible' => 'Les usagés en gris sont non disponibles, ceux barré n\'ont pas les pré-requis du cours.',
  'evenement.titre.a' => 'À',
  'evenement.titre.evenement' => 'Evenement',
  'evenement.titre.formation' => 'Formation',
  'evenement.titre.moiMeme' => 'Moi-même',
  'evenement.titre.pour' => 'Pour',
  'formation.form.preRequis' => 'Sélectionner le ou les pré-requis de la formation.',
  'formation.plan.dateDebut' => 'Date et heure de début de la formation.',
  'formation.plan.dateFin' => 'Date et heure de fin de la formation.',
  'formation.plan.instituteur' => 'Sélectionner le ou les instituteurs de la formation.',
  'formation.plan.moniteur' => 'Sélectionner le ou les moniteurs de la formation.',
  'groupe.form.caserne' => 'Sélectionner la caserne où l\'équipe sera utilisée.',
  'message.form.listeDestinataire' => 'Liste des usagers qui recevront le message.',
  'message.form.viderListe' => 'Vide la liste des destinataires.',
  'minimum.form.caserne' => 'Sélectionner la caserne où l\'exception sera prise en compte.',
  'minimum.form.dateDebut' => 'Date de début de l\'exception.',
  'minimum.form.dateFin' => 'Date de fin de l\'exception.',
  'minimum.form.minimum' => 'Minimum de l\'exception',
  'minimum.form.niveauAlerte' => 'Inscriver le nombre d\'équipe à inclure dans le calcul des minimums.',
  'notice.form.caserne' => 'Sélectionner la ou les casernes où la notice apparaitra.',
  'poste.form.formationObligatoire' => 'Cocher pour que seul les pompiers pouvant occuper ce poste sois sugérer lors de la création d\'horaire.',
  'usager.form.ajouterPhotoProfil' => 'Pour ajouter une photo au profil de l\'usager, commencer par charger la photo en cliquant sur le bouton "Select a file"',
  'usager.form.ajusterPhotoProfil' => 'Si la photo n\'est pas de la bonne taille, vous pouvez cliquez sur "Ajuster la photo" afin de la recadrer',
  'usager.form.caserne' => 'En choisissant une caserne dans ce menu déroulant, vous pourrez associer cet usager aux équipes et groupes de cette caserne dans l\'encadré plus bas',
  'usager.form.gestionDroits' => 'Choisissez le niveau d\'accès que l\'utilisateur a besoin.',
  'usager.form.gestionHoraire' => 'Cocher cette case pour permettre à cet usager de créer, valider et modifier des horaires.',
  'usager.form.photoProfil' => 'Ce formulaire vous permet d\'ajouter une photo de profil à l\'usager. Lors de l\'opération, vous pourrez recadrer l\'image à la taille requise par le système.',
  'notice.form.dateDebut' => 'Date à partir de laquelle la notice sera affichée aux pompiers',
  'notice.form.dateFin' => 'Date de retrait de la notice dans le système. Elle demeure accessible pour l\'administrateur',
);
